### PR TITLE
feat(commence): check plain html rendering

### LINKED ISSUE #53: Emergency stop switch: check plain html rendition
The "dead man switch" that blocks purging when something is wrong with Helix Pages currently checks the full rendition of `OK.md` against a static copy. This includes metadata tags with GH branches exposed in the URLs. This was the reason for a regression (see #50) and might cause further issues in the future.

Checking against a plain html rendition instead (`/OK.plain.html`) would be more streamlined, branch-safe and require less frequent updates of the static copy.

### PR DESCRIPTION
**Pull request by rofe**
Fix #53

### CODE REVIEW

**Review by trieloff — APPROVED** [review]
That's cheating! I like it!

**Comment by rofe** [comment]
@trieloff do you think there are instances where this may create a false sense of security?

**Comment by rofe** [comment]
@tripodsan's https://github.com/adobe/helix-purge/issues/53#issuecomment-726640775 suggests that...

**Comment by trieloff** [comment]
Yes, the risk of false negatives is increased with this approach, but I think it is more maintainable.

**Comment by rofe** [comment]
@davidnuescheler wdyt? iirc you had given a 👍 in Slack...

**Comment by davidnuescheler** [comment]
i am torn in the same way as @trieloff outlines, false negatives vs. maintenance. 
i don't really care that much though, so if someone feels strongly i am easily swayed.

**Comment by trieloff** [comment]
I'm not torn. Let's try it and iterate when we find out how much of an issue this really is.

**Pull request merged**
