### PR TITLE
feat: remove surrogate key purging and stop switch

### LINKED ISSUE #105: "Not purging inner CDN for null due to missing fastly credentials"
**Description**
As of 1.5.14 we're seeing the following error msg in the logs: 
```
Not purging inner CDN for null due to missing fastly credentials
```

Logs: https://helix.coralogix.com/#/query/logs?id=2GMiohKfrn3

Looking at the [code](https://github.com/adobe/helix-purge/blob/main/src/index.js#L98-L108) it seems that at least `host` and `path` are null. 

@trieloff Regression of https://github.com/adobe/helix-purge/pull/103

**Version:**
`helix-purge` `1.5.14`

### LINKED ISSUE #133: Remove dead-man switch
And use the purge stop in helix-publish instead: adobe/helix-publish#765

### LINKED ISSUE #189: Remove surrogate key purging
There is currently no added value in having asynchronous surrogate key purging in addition to the `PURGE` calls.

cc @davidnuescheler @trieloff

### PR DESCRIPTION
**Pull request by rofe**
Fix #189 
Fix #133 
Fix #105

### CODE REVIEW

**Comment by davidnuescheler** [comment]
i think this is great @rofe, thanks a lot.
i want to make sure that we also clean up a couple of other things... 

i think we should disallow access to purge directly to the runtime and implement a global "switch" (not dead man) possibly with a edge dict entry on `.page`

**Comment by rofe** [comment]
> i think we should disallow access to purge directly to the runtime and implement a global "switch" (not dead man) possibly with a edge dict entry on `.page`

See https://github.com/adobe/helix-publish/issues/765

**Comment by stefan-guggisberg** [comment]
> > i think we should disallow access to purge directly to the runtime and implement a global "switch" (not dead man) possibly with a edge dict entry on `.page`
> 
> See [adobe/helix-publish#765](https://github.com/adobe/helix-publish/issues/765)

I haven't participated in the discussion and don't know the exact reasons for this change. Therefore I can't review this PR.

The above issue mentions implementing a global "switch" as an entry in the `secrets` edge dict on `hlx.page`. The `secrets` dict can't be edited in the Fastly UI. Is that intended?

**Comment by rofe** [comment]
> I haven't participated in the discussion and don't know the exact reasons for this change. Therefore I can't review this PR.

@stefan-guggisberg let me give give you more context. This PR aims to solve 2 problems:
1. Stop/dead man switch: the current implementation always renders a `hlx.page` resource which can take a while in order check if it's OK to purge. At the same time, it doesn't really shield against the majority of outages which are mostly very short-lived (it could very well happen that the dead man switch says it's OK to purge, and the next request fails or vice versa). Therefore it was decided (a while back) to replace it with an edge dict based solution. see #133 and linked issues.
2. API purging: The way we are using `helix-purge` today calls for synchronous execution. Especially the _Sidekick > Reload_ functionality which needs to load the latest state of a document from the backend. Initially, the inner CDN was purged via API only, which can led to inconsistencies because it's asynchronous. Since #112, we are therefore even always purging the inner CDN twice: once via API, and once via `PURGE` method. The latter is doing its job, and the earlier is considered obsolete, at least at the moment.

**Review by trieloff — APPROVED** [review]

**Comment by trieloff** [comment]
See also: https://github.com/adobe/project-helix/pull/548

**Pull request merged**
